name: tflint
on:
  pull_request:
    paths:
      - '.github/workflows/tflint.yml'
      - '**/**.tf'
jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: terraform-linters/setup-tflint@v3
      - run: tflint --recursive --format compact      