name: tflint
on:
  pull_request:
    paths:
      - '.github/workflows/tflint.yml'
      - '**/**.tf'
jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: info
          filter_mode: nofilter
          fail_on_error: true
          flags: "--recursive --config=${{ github.workspace }}/terraform/.tflint.hcl"