name: tflint
on:
  pull_request:
    paths:
      - '.github/workflows/tflint.yml'
      - '**/**.tf'
jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
          flags: --recursive
          level: info
