name: yamlfmt
on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.yaml'
      - '**/*.yml'
jobs:
  yamlfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yamlfmt
        shell: bash
        run: |-
          wget https://github.com/google/yamlfmt/releases/download/v0.10.0/yamlfmt_0.10.0_Linux_x86_64.tar.gz
          tar -xf yamlfmt_0.10.0_Linux_x86_64.tar.gz
          ./yamlfmt .
